### ISSUE TITLE
Transition this site to demos.mapbox.com

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/x-files#12]
We're going to transition this repo's website to the `demos.mapbox.com` subdomain.

I just added a publisher-staging branch and deployed the site to the staging location https://demos.tilestream.net/x-files/

Next steps:

- [x] Launch the website at `demos.mapbox.com`.
- [x] Create a 301 redirect.
- ~Search for and update references to the `www` URL.~ (No references found.)
- [x] Delete the `www` site version(s) and their corresponding branches.

cc @mapbox/sales-engineering @mapbox/frontend-platform

**Comment by danswick** [comment]
![](https://media.giphy.com/media/3oEduFtDJYToVby97G/giphy.gif)

**Comment by davidtheclark** [comment]
Ok, this transition is complete. The www site files will be deleted the next time www.mapbox.com is deployed.
